spring:
  application:
    name: iqtest

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

payment:
  toss:
    base_url: https://api.tosspayments.com
    secret: ${TOSS_SECRET_KEY}
