spring:
  application:
    name: iqtest

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

payment:
  toss:
    base_url: https://api.tosspayments.com
    secret: ${TOSS_SECRET_KEY}
