spring:
  application:
    name: iqtest

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          debug: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

payment:
  nice:
    #    테스트 url
    base_url: https://sandbox-api.nicepay.co.kr
    #    테스트 시크릿 키
    secret: ${NICE_SECRET_KEY}
  toss:
    base_url: https://api.tosspayments.com
    secret: ${TOSS_SECRET_KEY:tmp_secret}

logging:
  file:
    path: ${LOG_BASE:/logs}
