name: Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Create .env file
        run: |
          cat <<EOF > .env
          MYSQL_URL=${{ secrets.MYSQL_URL }}
          MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }}
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          TOSS_SECRET_KEY=${{ secrets.TOSS_SECRET_KEY }}
          LOG_BASE=${{ secrets.LOG_BASE }}
          EOF

      - name: Send .env to EC2
        run: |
          scp -i ~/.ssh/id_ed25519 .env ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/brainbrain-backend/.env

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "cd ~/brainbrain-backend && git pull && ./deploy.sh"
